function compile_mex
%    mex t_gofr_m.cpp...
%        /home/tcaswell/intel/ipp/5.3.3.075/em64t/sharedlib/libippsem64t.so...
%        /home/tcaswell/intel/ipp/5.3.3.075/em64t/sharedlib/libippvmem64t.so...
%        -I/home/tcaswell/intel/ipp/5.3.3.075/em64t/include
%    
    
       mex t_hello.cpp ...
       /home/tcaswell/intel/ipp/5.3.3.075/em64t/sharedlib/libippsem64t.so...
       /home/tcaswell/intel/ipp/5.3.3.075/em64t/sharedlib/libippiem64t.so...
       /home/tcaswell/intel/ipp/5.3.3.075/em64t/sharedlib/libippvmem64t.so...
       /home/tcaswell/plutarc/plu_CenterFind/source/image1.cpp...
       /home/tcaswell/plutarc/plu_CenterFind/source/params1.cpp...
       /home/tcaswell/plutarc/plu_CenterFind/source/kernel1.cpp...
       /home/tcaswell/plutarc/plu_CenterFind/source/data_proc1.cpp  ...
       -I/home/tcaswell/intel/ipp/5.3.3.075/em64t/include...
       -I/home/tcaswell/plutarc/plu_CenterFind/source
   