function out = dummy_fun(fname)
   
    frames = 100;
    max_r = 4;
    offset = 500;
    trim = 90;
    corc = 1;
    
    output = open(fname);
    tmp = output.all_pks_trim(:,[2 3 end]);
    out.stack_name = output.fname;
    tmp(:,3) = tmp(:,3) -1;
    clear output
    
    

    
    tmp = tmp(tmp(:,3)<(frames+offset) & tmp(:,3)>=offset,:);
    tmp(:,3) = tmp(:,3) - offset;
    out.offset = offset;
    out.max_r = max_r;
    out.trim = trim;
    out.corc = corc;
% $$$     
% $$$     out.edge_hist = zeros(1,21)';
% $$$     out.area_hist = zeros(1,151)';
% $$$     for j = 0:(max(tmp(:,3)))
% $$$         [a b] = voronoin(unique(tmp(tmp(:,end)==j,[1 2]),'rows'));
% $$$         out.area_hist = out.area_hist +...
% $$$             histc(cellfun(@(x) polyarea(a(x,1),a(x,2)),b),0:1:150);
% $$$         
% $$$         out.edge_hist =out.edge_hist...
% $$$             + histc(cellfun(@(x) size(x,2),b),0:1:20);
% $$$     end
% $$$        
% $$$     out.edge_hist =out.edge_hist/size(tmp,1);
% $$$     out.area_hist =out.area_hist/size(tmp,1);
    
% $$$     [out.Drr_a  out.Drr_b...
% $$$      out.Drr2_a out.Drr2_b...
% $$$      out.Dxx_a  out.Dxx_b...
% $$$      out.Dtt_a  out.Dtt_b...
% $$$      out.Dyy_a  out.Dyy_b...
% $$$     ] = test(tmp);toc;
    [out.v1.mean_frame_disp...
     out.v1.md...
     out.v1.md_count...
     out.v1.msd...
     out.v1.msd_count...
     out.v1.msd_sq...
     out.v1.msd_sq_count...
    ] = test1(tmp,520,1390,frames,max_r,trim,corc);toc;
    [out.v2.mean_frame_disp...
     out.v2.md...
     out.v2.md_count...
     out.v2.msd...
     out.v2.msd_count...
     out.v2.msd_sq...
     out.v2.msd_sq_count...
    ] = test2(tmp,520,1390,frames,max_r,trim,corc);toc;
    [out.v3.mean_frame_disp...
     out.v3.md...
     out.v3.md_count...
     out.v3.msd...
     out.v3.msd_count...
     out.v3.msd_sq...
     out.v3.msd_sq_count...
    ] = test3(tmp,520,1390,frames,max_r,trim,corc);toc;
toc;
    clear test1;
    clear test2;
    clear test3;
    clear tmp;
    
end