function out = mex_corrs(fname)
   
    output = open(fname);
    
    tmp = output.all_pks_trim(:,[2 3 end]);
    tmp(:,3) = tmp(:,3) -1;
    out.stack_name = output.fname;
    out.fname = fname;
    clear output

    frames = 50;
    offset = 650;
    tmp = tmp(tmp(:,3)<(frames+offset) & tmp(:,3)>=offset,:);
    tmp(:,3) = tmp(:,3) - offset;
    
    tic; [out.md,         ...
          out.md_c,   ...
          out.msd,        ...
          out.msd_c,  ...
          out.msd_sq,     ...
          out.msd_sq_c    ...
          out.Duu,        ...
          out.Duu_c,      ...
          out.DuuL,       ...
          out.DuuL_c,     ...
          out.DuuT,       ...
          out.DuuT_c,     ...
          out.Ddrdr,      ...
          out.Ddrdr_c     ...
          out.Ddudu,      ...
          out.Ddudu_c]    ...
            = corr_test(tmp,520,1390,frames,6);toc;

    clear corr_test;
    
% $$$     s_name = ['corrs_' fname((find(fname =='/',1,'last')+11):(find(fname ...
% $$$                                                       =='.',1,'last')-1)) ...
% $$$               '.mat']
% $$$     eval(sprintf('save %s out',s_name))
    
    end