function print_meta(metaD,fname)
%o function print_meta(metaD)
%o summary: prints out a nx2 cell array of key:value pairs
%o input:
%-metaD:xn2 cell array, such as that generated by getall_meta
%-[opt]fname: file to write data to, default is to screen
%if the file exists it WILL BE over written!!
%o output:
%no values returned, data printed, or saved
    fid = 1;
    if nargin>1
        fid = fopen(fname,'w');
    end
    
    for j = 1:size(metaD,1);
        fprintf(fid,'%s: %s \n',metaD{j,1},metaD{j,2});
    end;
    
    if fid ~=1
        fclose(fid)
    end
end
    